# Token for API
wstoken: wstoken

# Login parameters
# Use only one of "api_only / raw / username_passwd / graphical / rwth" is supported
login:
  # # api_only provides limited functionality
  # type: ApiOnly
  # url: http://moodle.example.com
  # raw (Intended primarily for development)
  type: Raw
  url: http://moodle.example.com
  cookie: cookie
  # # graphical (opens a browser window to log in)
  # type: Graphical
  # url: http://moodle.example.com
  # # user_pass
  # type: UserPass
  # url: http://moodle.example.com
  # username: username
  # password: passwd
  # # RWTH specific SSO implementation
  # type: Rwth
  # username: name
  # password: pass
  # totp: totp
  # totp_secret: totpsecret

# Courses
courses:
  - id: 12345
    name: math
  - id: 12346
    name: english

### Additional Options for fine tuning

# Modules to sync
modules:
  - Resource
  - Folder
  - Pdfannotator
  # Assignments:
  - Assign
  - Label
  - Url
  - Page
  - Quiz
  - Feedback
  - Glossary
  - Vpl
  # Currently Lti is equivalent to opencast
  - Lti
  - Forum
  - Hsuforum
  - Grouptool

# Enables saving points
points: true

# One of keep "None / Update / Archive"
update_strategy: Archive

# Optionally set path of chrome executable (instead of autodetect
# (may be removed)
#chrome_executable: /usr/bin/chromium-browser

# Enables downloading youtube videos (may be removed)
youtube:
  path: /bin/usr/yt-dlp
  params:
    - -N
    - 4
  parallel_downloads: 2

# How webpages should be saved (only one)
page_conversion:
  # Use the sing-file tool to convert it to an html-document
  type: SingleFile
  path: /path/to/single-file
  # # Store entire file as pdf with a single page
  # type: SinglePage
  # # Standard chrome pdf
  # type: Standard

# Optional: Dir to sync to (may be removed)
# dir: ./cool/path

# Optional: Dir to sync to (may be removed)
log_file: moo-dl.log

# Optional: Regex to filter out files
file_filters:
  # - reg1
  # - reg2
