# Token for API
wstoken: wstoken
# Your moodle user id (needed for some operations)
user_id: 1234

# Login parameters
# Use only one of "api_only / raw / username_passwd / graphical / rwth" is supported
login:
  # # api_only provides limited functionality
  # type: ApiOnly
  # url: http://moodle.example.com
  # raw (Only intended for development)
  # Do NOT use this in production, it will cause moo-dl to fully crash
  type: Raw
  url: http://moodle.example.com
  cookie: cookie
  # # graphical (opens a browser window to log in)
  # type: Graphical
  # url: http://moodle.example.com
  # # user_pass
  # type: UserPass
  # url: http://moodle.example.com
  # username: username
  # password: passwd
  # # RWTH specific SSO implementation
  # type: Rwth
  # username: name
  # password: pass
  # totp: totp
  # totp_secret: totpsecret

# Courses
# You get get the course ids by opening the course in your webbrowser with the id being the number after "id="
# Example The id in "https://moodle.example/course/view.php?id=1234" is "1234"
courses:
  - id: 12345
    name: math
  - id: 12346
    name: english

### Additional Options for fine tuning

# Modules to sync
modules:
  - Resource
  - Folder
  - Pdfannotator
  # Assignments:
  - Assign
  - Label
  - Url
  - Page
  #- Quiz
  - Glossary
  #- Vpl
  # Currently Lti is equivalent to opencast (which requires youtube to be enabled)
  - Lti
  - Grouptool

# Enables saving grades
grades: true

# One of keep "None / Update / Archive"
update_strategy: Archive

# Optionally set path of chrome executable (instead of autodetect
# (may be removed)
#chrome_executable: /usr/bin/chromium-browser

# Enables downloading youtube videos (may be removed)
youtube:
  path: /bin/usr/yt-dlp
  params:
    - -N
    - 4
  parallel_downloads: 2

# How webpages should be saved (only one)
page_conversion:
  # Use the sing-file tool to convert it to an html-document
  type: SingleFile
  path: /path/to/single-file
  # # Store entire file as pdf with a single page
  # type: SinglePage
  # # Standard chrome pdf
  # type: Standard

# Optional: Dir to sync to (may be removed)
# dir: ./cool/path

# Optional: Dir to sync to (may be removed)
log_file: moo-dl.log

# Optional: Regex to filter out files
# Warning: These only get applied for files directly served by the api,
#            to filter other files please remove the corresponding modules directly
file_filters:
  # - reg1
  # - reg2
